server:
  port: '${PORT:8092}'
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:h2:mem:mydb'
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  require-ssl: true
  
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true  
    nonSecurePortEnabled: false 
    secureVirtualHostName: ${spring.application.name}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
    metadataMap:
      hostname : ${eureka.instance.hostname}
      securePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: 'https://localhost:8760/eureka/'
    tls:
      enabled: true
      key-store: classpath:books.p12
      key-store-type: PKCS12
      key-store-password: mypass
      key-password: mypass
      trust-store: classpath:books.p12
      trust-store-type: PKCS12
      trust-store-password: mypass
            
myproperty: value1234
      
