server:  
  port: ${PORT:8081}
  
spring:
  mvc:
     pathmatch:
        matching-strategy: ant_path_matcher
  security:
     user:
        name: username
        password: pass
  rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest 
   
management:
   endpoint: 
      health:
         show-details: always
   endpoints: 
      web:
         exposure:
            include: '*'

myproperty: value22222

myproperties:
   properties:
      - value1
      - value2
      
