server:  
  port: ${PORT:8081}

myproperty: value 

myproperties:
   properties:
      - value1
      - value2
      
spring:
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest 