server:
   port: ${PORT:8760}

spring:
   security:
      user:
         name: myusername
         password: mypassword
      require-ssl: true
               
eureka:
   instance:
      hostname: localhost
      securePort: ${server.port}
      securePortEnabled: true  
      nonSecurePortEnabled: false 
      homePageUrl: https://${eureka.instance.hostname}:${server.port}/
      statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
      healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
   client:
      registerWithEureka: false
      fetchRegistry: false
      
   tls:
      enabled: true
      client-auth: need
      key-store: classpath:discovery.p12
      key-store-type: PKCS12
      key-store-password: mypass
      trust-store: classpath:discovery.p12
      trust-store-type: PKCS12
      trust-store-password: mypass
